DLL 2020-10-27 16:44:26.429500 - PARAMETER dataset path : /data/object_detection  epochs : 1  batch size : 56  eval batch size : 32  no cuda : False  seed : None  checkpoint path : None  mode : benchmark-training  eval on epochs : [21, 31, 37, 42, 48, 53, 59, 64]  lr decay epochs : [43, 54]  learning rate : 0.0  momentum : 0.9  weight decay : 0.0005  lr warmup : None  backbone : resnet50  backbone path : None  num workers : 4  AMP : True  precision : amp 
Using seed = 937
loading annotations into memory...
Done (t=0.50s)
creating index...
index created!
/workspace/examples/ssd/src/coco_pipeline.py:63: DeprecationWarning: Argument 'output_dtype' for operator 'CropMirrorNormalize' is now deprecated. Use 'dtype' instead.
  pad_output=pad_output)
Traceback (most recent call last):
  File "main.py", line 287, in <module>
    train(train_loop_func, logger, args)
  File "main.py", line 153, in train
    train_loader = get_train_loader(args, args.seed - 2**31)
  File "/workspace/examples/ssd/src/data.py", line 35, in get_train_loader
    test_run = train_pipe.schedule_run(), train_pipe.share_outputs(), train_pipe.release_outputs()
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 680, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline:
Error when executing CPU operator COCOReader encountered:
[/opt/dali/dali/util/mmaped_file.cc:105] File mapping failed: /data/object_detection/train2017/000000069311.jpg
Stacktrace (10 entries):
[frame 0]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali.so(+0xc17ae) [0x7fe570f887ae]
[frame 1]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali.so(+0x1c2610) [0x7fe571089610]
[frame 2]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali.so(dali::FileStream::Open(std::string const&, bool, bool)+0x164) [0x7fe57107a334]
[frame 3]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x17bd900) [0x7fe549893900]
[frame 4]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x1811640) [0x7fe5498e7640]
[frame 5]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x1812584) [0x7fe5498e8584]
[frame 6]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x180bdc8) [0x7fe5498e1dc8]
[frame 7]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x1e885af) [0x7fe549f5e5af]
[frame 8]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7fe63476d6db]
[frame 9]: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fe634496a3f]

Current pipeline object is no longer valid.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'main.py', '--local_rank=0', '--mode', 'benchmark-training', '--data', '/data/object_detection', '--batch-size', '56', '--benchmark-warmup', '50', '--benchmark-iterations', '400', '--amp', '--learning-rate', '0']' returned non-zero exit status 1.
DONE!
