[2024-04-16 18:41:45,272] torch.distributed.run: [WARNING] 
[2024-04-16 18:41:45,272] torch.distributed.run: [WARNING] *****************************************
[2024-04-16 18:41:45,272] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-04-16 18:41:45,272] torch.distributed.run: [WARNING] *****************************************
7: thread affinity: {7, 135, 15, 143, 23, 151, 31, 159, 39, 167, 47, 175, 55, 183, 63, 191, 71, 199, 79, 207, 87, 215, 95, 223, 103, 111, 119, 127}
0: thread affinity: {0, 128, 134, 8, 136, 16, 144, 24, 152, 32, 160, 40, 168, 48, 176, 56, 184, 64, 192, 72, 200, 80, 208, 88, 216, 96, 104, 120}
2: thread affinity: {4, 132, 12, 140, 20, 148, 28, 156, 36, 164, 44, 172, 52, 180, 60, 188, 68, 196, 76, 204, 84, 212, 92, 220, 100, 108, 116, 124}
4: thread affinity: {1, 129, 9, 137, 17, 145, 25, 153, 33, 161, 41, 169, 49, 177, 57, 185, 65, 193, 73, 201, 81, 209, 89, 217, 97, 105, 113, 121}
5: thread affinity: {3, 131, 11, 139, 19, 147, 27, 155, 35, 163, 43, 171, 51, 179, 59, 187, 67, 195, 75, 203, 83, 211, 91, 219, 99, 107, 115, 123}
3: thread affinity: {6, 14, 142, 22, 150, 30, 158, 38, 166, 46, 174, 54, 182, 62, 190, 70, 198, 78, 206, 86, 214, 94, 222, 102, 110, 112, 118, 126}
6: thread affinity: {5, 133, 13, 141, 21, 149, 29, 157, 37, 165, 45, 173, 53, 181, 61, 189, 69, 197, 77, 205, 85, 213, 93, 221, 101, 109, 117, 125}
1: thread affinity: {2, 130, 10, 138, 18, 146, 26, 154, 34, 162, 42, 170, 50, 178, 58, 186, 66, 194, 74, 202, 82, 210, 90, 218, 98, 106, 114, 122}
Experiment dir : LM-TFM
Namespace(work_dir='LM-TFM', append_dataset=False, append_time=False, cuda=True, fp16=True, restart='', debug=False, log_all_ranks=False, dllog_file='train_log.json', txtlog_file='train_log.log', save_all=False, no_env=False, no_eval=True, no_test=False, log_interval=10, target_throughput=None, target_perplexity=None, apex_amp_opt_level='O2', amp='apex', affinity='socket_unique_interleaved', data='/data/transformer-xl/wikitext-103', dataset='wt103', vocab='word', n_layer=16, n_head=8, d_head=64, d_embed=512, d_model=512, d_inner=2048, dropout=0.1, dropatt=0.0, pre_lnorm=False, attn_type=0, not_tied=False, clamp_len=-1, adaptive=False, div_val=1, sample_softmax=-1, init='normal', emb_init='normal', init_range=0.1, emb_init_range=0.01, init_std=0.02, proj_init_std=0.01, optim='jitlamb', lr=0.0, mom=0.0, scheduler='cosine', max_step_scheduler=None, warmup_step=1000, decay_rate=0.5, lr_min=0.0, clip=0.25, weight_decay=0.0, clip_nonemb=False, patience=0, eta_min=0.001, max_step=400, batch_size=832, local_batch_size=None, batch_chunk=1, roll=True, tgt_len=192, ext_len=0, mem_len=192, seed=1111, multi_gpu=None, gpu0_bsz=-1, same_length=False, varlen=False, swap_mem=False, eval_tgt_len=192, eval_batch_size=16, eval_max_steps=-1, eval_interval=5000, local_rank=0, tied=True)
world size: 8
Collecting environment information...
[rank4]: Traceback (most recent call last):
[rank4]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 1134, in <module>
[rank4]:     main()
[rank4]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 778, in main
[rank4]:     corpus = get_lm_corpus(args.data, args.dataset, args.vocab)
[rank4]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 322, in get_lm_corpus
[rank4]:     corpus = Corpus(datadir, dataset, vocab, **kwargs)
[rank4]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 247, in __init__
[rank4]:     self.vocab.count_file(os.path.join(path, 'train.txt'))
[rank4]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/utils/vocabulary.py", line 58, in count_file
[rank4]:     assert os.path.exists(path)
[rank4]: AssertionError
[rank6]: Traceback (most recent call last):
[rank6]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 1134, in <module>
[rank6]:     main()
[rank6]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 778, in main
[rank6]:     corpus = get_lm_corpus(args.data, args.dataset, args.vocab)
[rank6]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 322, in get_lm_corpus
[rank6]:     corpus = Corpus(datadir, dataset, vocab, **kwargs)
[rank6]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 247, in __init__
[rank6]:     self.vocab.count_file(os.path.join(path, 'train.txt'))
[rank6]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/utils/vocabulary.py", line 58, in count_file
[rank6]:     assert os.path.exists(path)
[rank6]: AssertionError
[rank1]: Traceback (most recent call last):
[rank1]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 1134, in <module>
[rank1]:     main()
[rank1]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 778, in main
[rank1]:     corpus = get_lm_corpus(args.data, args.dataset, args.vocab)
[rank1]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 322, in get_lm_corpus
[rank1]:     corpus = Corpus(datadir, dataset, vocab, **kwargs)
[rank1]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 247, in __init__
[rank1]:     self.vocab.count_file(os.path.join(path, 'train.txt'))
[rank1]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/utils/vocabulary.py", line 58, in count_file
[rank1]:     assert os.path.exists(path)
[rank1]: AssertionError
[rank5]: Traceback (most recent call last):
[rank5]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 1134, in <module>
[rank5]:     main()
[rank5]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 778, in main
[rank5]:     corpus = get_lm_corpus(args.data, args.dataset, args.vocab)
[rank5]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 322, in get_lm_corpus
[rank5]:     corpus = Corpus(datadir, dataset, vocab, **kwargs)
[rank5]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 247, in __init__
[rank5]:     self.vocab.count_file(os.path.join(path, 'train.txt'))
[rank5]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/utils/vocabulary.py", line 58, in count_file
[rank5]:     assert os.path.exists(path)
[rank5]: AssertionError
[rank2]: Traceback (most recent call last):
[rank2]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 1134, in <module>
[rank2]:     main()
[rank2]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 778, in main
[rank2]:     corpus = get_lm_corpus(args.data, args.dataset, args.vocab)
[rank2]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 322, in get_lm_corpus
[rank2]:     corpus = Corpus(datadir, dataset, vocab, **kwargs)
[rank2]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 247, in __init__
[rank2]:     self.vocab.count_file(os.path.join(path, 'train.txt'))
[rank2]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/utils/vocabulary.py", line 58, in count_file
[rank2]:     assert os.path.exists(path)
[rank2]: AssertionError
[rank3]: Traceback (most recent call last):
[rank3]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 1134, in <module>
[rank3]:     main()
[rank3]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 778, in main
[rank3]:     corpus = get_lm_corpus(args.data, args.dataset, args.vocab)
[rank3]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 322, in get_lm_corpus
[rank3]:     corpus = Corpus(datadir, dataset, vocab, **kwargs)
[rank3]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 247, in __init__
[rank3]:     self.vocab.count_file(os.path.join(path, 'train.txt'))
[rank3]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/utils/vocabulary.py", line 58, in count_file
[rank3]:     assert os.path.exists(path)
[rank3]: AssertionError
PyTorch version: 2.3.0a0+40ec155e58.nv24.03
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.28.3
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-102-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.4.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H100 80GB HBM3
GPU 1: NVIDIA H100 80GB HBM3
GPU 2: NVIDIA H100 80GB HBM3
GPU 3: NVIDIA H100 80GB HBM3
GPU 4: NVIDIA H100 80GB HBM3
GPU 5: NVIDIA H100 80GB HBM3
GPU 6: NVIDIA H100 80GB HBM3
GPU 7: NVIDIA H100 80GB HBM3

Nvidia driver version: 535.161.08
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.0.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      46 bits physical, 57 bits virtual
Byte Order:                         Little Endian
CPU(s):                             224
On-line CPU(s) list:                0-223
Vendor ID:                          GenuineIntel
Model name:                         Intel(R) Xeon(R) Platinum 8480+
CPU family:                         6
Model:                              143
Thread(s) per core:                 2
Core(s) per socket:                 56
Socket(s):                          2
Stepping:                           8
BogoMIPS:                           4000.00
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities
Virtualization:                     VT-x
L1d cache:                          5.3 MiB (112 instances)
L1i cache:                          3.5 MiB (112 instances)
L2 cache:                           224 MiB (112 instances)
L3 cache:                           210 MiB (2 instances)
NUMA node(s):                       2
NUMA node0 CPU(s):                  0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,102,104,106,108,110,112,114,116,118,120,122,124,126,128,130,132,134,136,138,140,142,144,146,148,150,152,154,156,158,160,162,164,166,168,170,172,174,176,178,180,182,184,186,188,190,192,194,196,198,200,202,204,206,208,210,212,214,216,218,220,222
NUMA node1 CPU(s):                  1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95,97,99,101,103,105,107,109,111,113,115,117,119,121,123,125,127,129,131,133,135,137,139,141,143,145,147,149,151,153,155,157,159,161,163,165,167,169,171,173,175,177,179,181,183,185,187,189,191,193,195,197,199,201,203,205,207,209,211,213,215,217,219,221,223
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] onnx==1.15.0rc2
[pip3] onnxruntime==1.17.3
[pip3] optree==0.10.0
[pip3] pytorch-quantization==2.1.2
[pip3] pytorch-transformers==1.1.0
[pip3] pytorch-triton==2.2.0+e28a256d7
[pip3] torch==2.3.0a0+40ec155e58.nv24.3
[pip3] torch-tensorrt==2.3.0a0
[pip3] torchdata==0.7.1a0
[pip3] torchtext==0.17.0a0
[pip3] torchvision==0.18.0a0
[conda] Could not collect
Producing dataset wt103...
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 1134, in <module>
[rank0]:     main()
[rank0]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 778, in main
[rank0]:     corpus = get_lm_corpus(args.data, args.dataset, args.vocab)
[rank0]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 322, in get_lm_corpus
[rank0]:     corpus = Corpus(datadir, dataset, vocab, **kwargs)
[rank0]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 247, in __init__
[rank0]:     self.vocab.count_file(os.path.join(path, 'train.txt'))
[rank0]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/utils/vocabulary.py", line 58, in count_file
[rank0]:     assert os.path.exists(path)
[rank0]: AssertionError
[rank7]: Traceback (most recent call last):
[rank7]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 1134, in <module>
[rank7]:     main()
[rank7]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/train.py", line 778, in main
[rank7]:     corpus = get_lm_corpus(args.data, args.dataset, args.vocab)
[rank7]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 322, in get_lm_corpus
[rank7]:     corpus = Corpus(datadir, dataset, vocab, **kwargs)
[rank7]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/data_utils.py", line 247, in __init__
[rank7]:     self.vocab.count_file(os.path.join(path, 'train.txt'))
[rank7]:   File "/workspace/benchmark/LanguageModeling/Transformer-XL/pytorch/utils/vocabulary.py", line 58, in count_file
[rank7]:     assert os.path.exists(path)
[rank7]: AssertionError
[2024-04-16 18:42:15,309] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 5195) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 834, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 825, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 137, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 271, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-04-16_18:42:15
  host      : d91aa8e7cb21
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 5196)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-04-16_18:42:15
  host      : d91aa8e7cb21
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 5197)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-04-16_18:42:15
  host      : d91aa8e7cb21
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 5198)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-04-16_18:42:15
  host      : d91aa8e7cb21
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 5199)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-04-16_18:42:15
  host      : d91aa8e7cb21
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 5200)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-04-16_18:42:15
  host      : d91aa8e7cb21
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 5201)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2024-04-16_18:42:15
  host      : d91aa8e7cb21
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 5202)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-16_18:42:15
  host      : d91aa8e7cb21
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 5195)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
DONE!
